server:
  port: 8080

spring:
  application:
    name: temporal-demo
  datasource:
    url: jdbc:mysql://localhost:3306/bisbis10?useSSL=false
    user name: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update